name: Test PHP benchmark
on: [ push, pull_request ]

jobs:
  setup:
    runs-on: ubuntu-22.04
    
    steps:
    
    - uses: actions/checkout@v3

    - name: Install WRK
      run: sudo apt-get install wrk w3m

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: dom, curl, libxml, mbstring, zip, pcntl, ctype, iconv
        coverage: none
    
    - name: Install Apache mod_php
      run: |
          LC_ALL=C.UTF-8 sudo apt-add-repository http://ppa.launchpad.net/ondrej/php/ubuntu
          sudo apt install libapache2-mod-php8.2
          sudo a2enmod php8.2 rewrite
      shell: bash
    
    - name: Setup frameworks
      run: bash setup.sh

    - name: Copy files to web root
      run: |
        sudo mkdir /var/www/html/PHP-Frameworks-Bench
        sudo cp -R ./* /var/www/html/PHP-Frameworks-Bench/
    
    - name: Restart apache server
      run: sudo service apache2 restart
    
    - name: Check frameworks
      run: bash check.sh
    